"""Changes column maturity to current price

Revision ID: 209bd11fe326
Revises: a9fb1cb9d931
Create Date: 2023-10-05 02:39:05.011039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209bd11fe326'
down_revision = 'a9fb1cb9d931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price_per_share', sa.Integer(), nullable=True))
        batch_op.drop_column('term_to_maturity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_to_maturity', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('current_price_per_share')

    # ### end Alembic commands ###
