"""connecting many to many

Revision ID: a9fb1cb9d931
Revises: 
Create Date: 2023-09-28 15:11:25.345558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fb1cb9d931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('shares_quantity', sa.Integer(), nullable=True),
    sa.Column('price_per_share', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_stock_portfolio_id_portfolios')),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_portfolio_stock_stock_id_stocks')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_portfolios_stock_id_stocks', type_='foreignkey')
        batch_op.drop_column('stock_id')
        batch_op.drop_column('price_per_share')
        batch_op.drop_column('shares_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares_quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('price_per_share', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('stock_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_portfolios_stock_id_stocks', 'stocks', ['stock_id'], ['id'])

    op.drop_table('portfolio_stock')
    # ### end Alembic commands ###
